### ISSUE TITLE
virtualenv description gently misleading

### ISSUE THREAD

**Issue by akx** [cs01/python-packaging-tools#16]
> This is essentially a 3rd party package that duplicates the standard libary venv module

is not exactly true these days; `virtualenv` 20.0.0+ has various tricks up its sleeve which make creating virtualenvs much faster than the stock module.

**Comment by cs01** [comment]
Thanks, I gave the descriptions my best shot, but I am not able to keep current on everything. Want to file a pull request with what you think would be better?
