### ISSUE TITLE
Proposal: add pip-audit

### ISSUE THREAD

**Issue by woodruffw** [cs01/python-packaging-tools#50]
Hey there! Thanks a ton for maintaining this list and site; I think it's an awesome idea 🙂 

As one of the maintainers of `pip-audit`, I'm submitting it for consideration: `pip-audit` is a tool for auditing dependency sources (packaging files, active environments, etc.) for known dependencies (i.e., ones submitted to the PyPA security advisory DB or other open-source DBs).

Repo: https://github.com/trailofbits/pip-audit/

PyPI: https://pypi.org/project/pip-audit/

I'm happy to issue a corresponding PR, if you're willing to include it!

**Comment by cs01** [comment]
Yeah sounds good! A PR would be great.

**Comment by woodruffw** [comment]
Awesome! I'll do that tonight.
